# Generated by Django 3.2.9 on 2021-12-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.category'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='company',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
