# Generated by Django 3.2.9 on 2021-12-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(upload_to='lego/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hook_text',
            field=models.CharField(max_length=100),
        ),
    ]
